spring:
  datasource:
    url: jdbc:postgresql://localhost:65432/demo_db
    username: fcc-spring-boot-demo-user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
